name: Quality Check Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        python -m pip install --upgrade poetry
    - name: Install project
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest